### ISSUE TITLE
Где взять исходники svg?

### ISSUE THREAD

**Issue by dmitrygorkun** [dvhb/metro#13]
Подскажите, а где брали исходники лебедевские в svg? Хочу переписать на новый ангуляр это

**Comment by alexbee** [comment]
@dmitrygorkun карту в svg готовили сами, на основе лебедевской. Можете взять за основу 
https://raw.githubusercontent.com/dvhb/metro/master/src/metro-moscow.svg. Если удалить `<div ng-transclude> </div>`, svg откроется в редакторе. Логика работы основана на id вида `id="l1"`, `id="s1l1"`.

**Comment by dmitrygorkun** [comment]
С логикой работы я разбирался и даже причесывал в пулреквесте структуру ) 
Просто боюсь, что сейчас эта версия ангуляра отмирает, и есть риск что разработка такой  шикарной карты заморозится...

**Comment by alexbee** [comment]
@dmitrygorkun у нас в планах запустить карту метро на react и vue, так как работаем сейчас с этими технологиями. Если нужна будет какая-то помощь, напиши в телеграмм @subbotenko
