### ISSUE TITLE
Не работает карта в IE

### ISSUE THREAD

**Issue by Overkloker** [dvhb/metro#2]
http://prntscr.com/beqitv

**Comment by anamuratova** [comment]
@alexbee возьми в работу, пожалуйста

**Comment by alexbee** [comment]
@Overkloker пришлите пожалуйста демку, в ie 11 карта метро должна работать – http://take.ms/6Ip5h

**Comment by Overkloker** [comment]
@alexbee http://kremk.ru/apartment нужно кликнуть по кнопке "Карта метро". http://prntscr.com/bfq788
login: demo
password: demo

**Comment by alexbee** [comment]
@Overkloker обновите пожалуйста версию карты метро до 0.4.0
