### ISSUE TITLE
На карте в ІЕ не выбираются станции.

### ISSUE THREAD

**Issue by jofreyswb** [dvhb/metro#3]
Если выбираем одну то ничего не происходит. А если выбрать там где их несколько то только тогда они выбираются - http://prntscr.com/c1hu4v

Где посмотреть неисправность:
http://kremk.ru/apartment нужно кликнуть по кнопке "Карта метро". http://prntscr.com/bfq788
login: demo
password: demo

**Comment by anamuratova** [comment]
@jofreyswb спасибо за репорт, на этой неделе планируем заняться этим багом

**Comment by i2m** [comment]
@jofreyswb обновитесь до версии 0.4.1
